### PR TITLE
shorten links in menu

### PR DESCRIPTION
**Pull request by ltalirz**
remove "API" from "API Documentation" and "API Specification" in order
to prevent overflow on Safari browser.

### CODE REVIEW

**Comment by CasperWA** [comment]
I guess @gmrigna will not be able to test it on his phone until it is merged and deployed in any case, right?

**Comment by gmrigna** [comment]
It was actually not on my phone, but on my MacBook...

**Comment by blokhin** [comment]
@ltalirz how should we proceed with that?

**Comment by ltalirz** [comment]
up to you - I resolved the conflict; feel free to merge

**Comment by rartino** [comment]
Sorry for not commenting until after this was merged, but were these shortened buttons still necessary to not overflow Safari after the changes I did? I released the max-width for the buttons, so there really should be no overflow until the window width is too small. (I also changed "API Documentation" to "API Docs", which is shorter than "Documentation"..., and dropped all icons.)

Isn't the 'API' part of these buttons quite clarifying? "Documentation" could really be about anything...

If you want to test the version before this merge in Safari, you can visit this link:
  https://rartino.github.io/materials-consortia.github.io/index

**Comment by ltalirz** [comment]
> Isn't the 'API' part of these buttons quite clarifying? "Documentation" could really be about anything...

Well, as stated on the homepage, Optimade is about developing a common REST API, so one could argue that "documentation" and "specification" are quite well defined.

Anyhow, I don't feel strongly about this change (that's why I didn't merge it), so feel free to revert.

**Comment by rartino** [comment]
I'll leave that up to @gmrigna. If we are anyway considering a major overhaul of the info provided, this isn't super-critical to revert now as the buttons are going to change with that.

**Pull request merged**
