### PR TITLE
Add Slack invitation link to "Get involved" section

### LINKED ISSUE #40: Add Slack invite link to website
Apparently, the only way to join the Slack channel is through an invitation.
So one can put an invitation link on the website for people to join it. 
If, for some reason we start to get a lot of bots or unwanted people we can take it down again - individual accounts can always be deactivated by the workspace owners as well (owners: @rartino, @ml-evs, @merkys, me, @dwinston (primary owner), @gmrigna, @shyamd).

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #40.

### CODE REVIEW

**Comment by CasperWA** [comment]
See the couple of lines here:
image

**Review by ml-evs — APPROVED** [review]

**Comment by blokhin** [comment]
Note, that the free tier of Slack permits only 10k messages being stored and publicly accessible. It's 9k now, so the oldest conversations will be lost relatively soon.

**Comment by gmrigna** [comment]
While we are at it, we may want to change the date of the next meeting to "Friday September 24th at  15:00 UTC/17:00 CEST"

**Comment by gmrigna** [comment]
There was a suggestion not to have a date in order to avoid this kind of situation in which the website is outdated... @ml-evs any suggestion?

**Comment by CasperWA** [comment]
> Note, that the free tier of Slack permits only 10k messages being stored and publicly accessible. It's 9k now, so the oldest conversations will be lost relatively soon.

Yeah - I don't think this will currently be an issue. Losing the old conversations I mean. It's much more important to keep the GitHub issue/PR discussions than the ones on Slack. It's mostly just discussions on immediate problems and even more informal than here.
But if it becomes more than that in the future we might need to think about either moving to another technology or from where we can get money to spend on it.

> While we are at it, we may want to change the date of the next meeting to "Friday September 24th at 15:00 UTC/17:00 CEST"

Ah, sorry. Already merged.

**Comment by ml-evs** [comment]
> While we are at it, we may want to change the date of the next meeting to "Friday September 24th at 15:00 UTC/17:00 CEST"

I've just committed this directly

**Pull request merged**
