### PR TITLE
Redesign with new logo

### PR DESCRIPTION
**Pull request by rartino**
This is an attempt to update the website with the new logo. I've also made a few other adjustments to avoid button overflow, etc.

You can see how it looks at: https://rartino.github.io/materials-consortia.github.io/index

I note that we presently do not seem to require review on our website. We probably should add the requirement of at least one review. In any case, I'll wait for a review before merging this.

Addresses #7 (but does not completely close it, since it is about updating the website for the release.)

### CODE REVIEW

**Comment by rartino** [comment]
@gmrigna Ok to merge? Or do you want to wait for checking with your graphics designer contact?

Once this is in place we really should start looking at the contents for a v1.0.0 release.

**Comment by gmrigna** [comment]
I will get an answer tomorrow... Basically, it is just about the color of the buttons. I am not sure that purple is the best choice (given that it also appears in the logo). My wife prefers a dark grey... but let us wait tomorrow.

**Comment by gmrigna** [comment]
Here is the answer of the graphic designer:
1) the filled buttons are better than those with just a frame around (earlier version)
2) the current version are "too present" and "kind of hide the logo" (just trying to translate from French)

Suggestion:
It is quite logical to use a color of the logo for the buttons. Red is also "too present", green looks "too gadget". Hence, we are left with the blue or some kind of gray.

**Comment by gmrigna** [comment]
My family would go for gray... Do you have other opinions at home?

**Comment by gmrigna** [comment]
[Screen Shot 2020-06-17 at 10.53.03.pdf](https://github.com/Materials-Consortia/materials-consortia.github.io/files/4791324/Screen.Shot.2020-06-17.at.10.53.03.pdf)

**Comment by gmrigna** [comment]
buttons_blue

**Comment by gmrigna** [comment]
buttons_gray

**Comment by muhrin** [comment]
Looks nice Gian-Marco.  I also prefer the grey over purple as the purple is a little intense.  Personally, I would also reduce the curvature radius of the buttons to make them look less cartoony.

**Comment by rartino** [comment]
Ok?

**Comment by muhrin** [comment]
Nice, I like it.

**Comment by gmrigna** [comment]
Great!

**Pull request merged**
