### PR TITLE
Streamline API specification page a bit

### PR DESCRIPTION
**Pull request by CasperWA**
Taking into account @ltalirz 's review comments for PR #3

### CODE REVIEW

**Comment by CasperWA** [comment]
Will continue discussion from PR #3 in this thread.
Latest comment from @ltalirz may be seen [here](https://github.com/Materials-Consortia/materials-consortia.github.io/pull/3#discussion_r305614139), and is cited explicitly also:

> @CasperWA Thanks for the PR with the changes!
> 
> Concerning this last point, I'm still not convinced.
> 
> For development purposes, optimade developers are, of course, free to implement whatever
> version (or non-version) of the spec they like (they will do this anyhow).
> I believe what we should write down here is what we recommend for _production_, including which version of an implementation a given optimade server SHOULD respond by default.
> 
> I believe it is very important that this be the latest _stable_ API version that was implemented, NOT a development version.
> 
> Note that the spec currently says:
> 
> > If the client does not include a version number in the base URL, the request is for the latest version of this standard that the database provider implements.
> 
> If this latest version is a development version, we are inviting a big mess since, as I mentioned before, a "development version" can refer to a spec any time from when the previous stable release was made to when the next version is released.

**Comment by CasperWA** [comment]
> For development purposes, optimade developers are, of course, free to implement whatever
> version (or non-version) of the spec they like (they will do this anyhow).
> I believe what we should write down here is what we recommend for _production_, including which version of an implementation a given optimade server SHOULD respond by default.

I think you're right for the website. However, note I lifted this text basically straight from the current README in the OPTiMaDe spec repo.

> I believe it is very important that this be the latest _stable_ API version that was implemented, NOT a development version.

Agree.

> Note that the spec currently says:
> 
> > If the client does not include a version number in the base URL, the request is for the latest version of this standard that the database provider implements.

I think this should actually be changed to explicitly state the latest _stable_ version.

The only thing I had rolling around in my head, when considering this, is our specific use of versioning within the specification (the `meta` response field and the `info` endpoint).
Yes, it may be that a developer implements a non-version, however, if they want to keep up with the latest developments from the `develop` branch of the specs, I simply wanted to state that they should implement it using the version listed at the top of the specs in this branch. Even if the version number is changed upon an official release.
However, I see that it would make sense to make sure the specs actually say to default to the latest _stable_ version.

**Comment by ltalirz** [comment]
> Yes, it may be that a developer implements a non-version, however, if they want to keep up with the latest developments from the develop branch of the specs, I simply wanted to state that they should implement it using the version listed at the top of the specs in this branch. Even if the version number is changed upon an official release.

I see, so perhaps one could reformulate it a bit - something like:

> If you are a **server** developer, it is _recommended_ to always implement the latest stable version. When implementing a development version, it is _recommended_ to label it as such using the `-develop` suffix.

Sounds good?

> However, I see that it would make sense to make sure the specs actually say to default to the latest stable version.

Agreed!
Let

**Comment by ltalirz** [comment]
@CasperWA happy to merge after the small update suggested above

**Comment by CasperWA** [comment]
> @CasperWA happy to merge after the small update suggested above

Done. Please review :+1:

**Pull request merged**
