### PR TITLE
Serve both with *www* and without *www*

### PR DESCRIPTION
**Pull request by blokhin**
Currently https://optimade.org does not work 😢 we need to fix that!

### CODE REVIEW

**Comment by blokhin** [comment]
NB using this **www** will be served "for free"

**Comment by rartino** [comment]
As far as I can see you've broken the website for everyone with this PR. I'm reverting.

This change won't work unless the people handling DNS for optimade.org makes the corresponding change! Which also isn't trivial, because one cannot CNAME the bare domain name. We've discussed this in #8.

Also, really, this really isn't a change that should be proposed and then merged within less than a day before people had a chance to react.

**Comment by blokhin** [comment]
Alright, I am keeping my eye on it. I suspected there is a DNS-record for the bare domain, but it's not the case:
```
root@vps11246:~# host -t a optimade.org
optimade.org has no A record
```

@gmrigna please, could you resolve it?

**Comment by blokhin** [comment]
So there should be four A records, pointing the apex domain to the IP addresses for [GitHub Pages](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain):
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
Then, there should be a CNAME Record, pointing `www` to `optimade.org.`
Then, finally, this PR can be applied. After that the website works both with **www** and without **www**.

**Comment by blokhin** [comment]
@gmrigna we need your help with the DNS configuration here

**Pull request merged**
