### PR TITLE
Add mention of and link to the OMDI2021 workshop

### PR DESCRIPTION
**Pull request by CasperWA**
Closes Materials-Consortia/omdi2021#14.

### CODE REVIEW

**Comment by CasperWA** [comment]
Looks like this (on my screen):
image

**Review by gmrigna — COMMENTED** [review]
You might as well remove the bit about the CECAM workshop... It will be over tomorrow.

**Comment by CasperWA** [comment]
> You might as well remove the bit about the CECAM workshop... It will be over tomorrow.

😭

**Comment by CasperWA** [comment]
> You might as well remove the bit about the CECAM workshop... It will be over tomorrow.

Please check the text in the [git diff](https://github.com/Materials-Consortia/materials-consortia.github.io/pull/39/files) if I should remove more.

**Review by gmrigna — APPROVED** [review]
Great!

**Pull request merged**
